# fly.toml app configuration file generated for pmlvietnam on 2026-09-15T13:58:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pmlvietnam'
primary_region = 'sin'

[build]

[env]
  HOSTNAME = '0.0.0.0'
  PORT = '8080'
  NEXT_PUBLIC_SITE_URL = 'https://pmlvietnam.vn'
  NEXT_PUBLIC_META_PIXEL_ID = '1458756179420493'
  NEXT_PUBLIC_GOOGLE_TAG_ID = 'G-B5CPN73ZCZ'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
